version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: tidal-db
    environment:
      POSTGRES_DB: tidal
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5432:5432"