spring:
  application:
    name: music
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:postgresql://localhost:5432/tidal
    username: user
    password: user
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true

tidal:
  client-id: ${TIDAL_CLIENT_ID:}
  client-secret: ${TIDAL_CLIENT_SECRET:}
  country-code: ${TIDAL_COUNTRY_CODE:DE}
  oauth2:
    redirect-uri: ${TIDAL_OAUTH2_REDIRECT_URI:http://localhost:8080/oauth2/callback}
